### ISSUE TITLE
Punctuations are not being converted

### ISSUE THREAD

**Issue by mgthantzin** [ha-shine/mm-unicoder#1] opened 2017-08-15 10:33 UTC
Specifically, comma, slash, back-slash, semi-colon, and square brackets are not being converted to Myanmar text.

**Comment by ha-shine** [comment] 2017-08-15 10:43
Can you show me an example? I am currently using windows built-in on-screen keyboard layout to check the character mapping. This is what I am seeing so far

![image](https://user-images.githubusercontent.com/10063033/29312799-a3123d54-81e9-11e7-8ea7-2d24511e78d9.png)

**Comment by mgthantzin** [comment] 2017-08-15 10:47
I've typed တယ် but ယ does not appear.

![screenshot_1](https://user-images.githubusercontent.com/137266/29312932-2ddf7190-81ea-11e7-9f84-ff08ebb7ee57.jpg)

I'm using Chrome on Windows and typing with hardware keyboard.

**Comment by ha-shine** [comment] 2017-08-15 10:53
It seems like microsoft doesn't acknowledge the existence of ယ
Can you show me where can I find proper keyboard layout?

**Comment by mgthantzin** [comment] 2017-08-16 01:36
You can probably check this out: [MyanSan Smart Input](http://www.myanmarlanguage.org/article/download-unicode-fonts-and-keyboards)

**Comment by ha-shine** [comment] 2017-08-25 06:01
First of all, sorry for late update.
I just realized there indeed is ယ in built-in Burmese keyboard from windows. It is `Shift+B`. I will be closing this issue for now as the converter is following the windows keyboard as intended.

**Closed as completed by ha-shine** 2017-08-25 06:01 UTC
